from visual_user import VisualUser, VisualNetwork, DEFAULT_NODE_COLOR

__author__ = 'Phillip Lemons'


## Network setup functions ################################
# Small Network
def network_1():
    A = VisualUser("A", DEFAULT_NODE_COLOR)
    B = VisualUser("B", DEFAULT_NODE_COLOR)
    C = VisualUser("C", DEFAULT_NODE_COLOR)
    D = VisualUser("D", DEFAULT_NODE_COLOR)
    E = VisualUser("E", DEFAULT_NODE_COLOR)
    F = VisualUser("F", DEFAULT_NODE_COLOR)
    G = VisualUser("G", DEFAULT_NODE_COLOR)
    H = VisualUser("H", DEFAULT_NODE_COLOR)
    I = VisualUser("I", DEFAULT_NODE_COLOR)
    J = VisualUser("J", DEFAULT_NODE_COLOR)

    A.add_student(B)
    A.add_student(C)
    A.add_student(D)
    B.add_student(E)
    B.add_student(F)
    C.add_student(F)
    D.add_student(G)
    H.add_student(J)
    I.add_student(J)

    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)
    net.add_user(H)
    net.add_user(I)
    net.add_user(J)

    return net


# Medium Network
def network_2():
    A = VisualUser("A", DEFAULT_NODE_COLOR)
    B = VisualUser("B", DEFAULT_NODE_COLOR)
    C = VisualUser("C", DEFAULT_NODE_COLOR)
    D = VisualUser("D", DEFAULT_NODE_COLOR)
    E = VisualUser("E", DEFAULT_NODE_COLOR)
    F = VisualUser("F", DEFAULT_NODE_COLOR)
    G = VisualUser("G", DEFAULT_NODE_COLOR)
    H = VisualUser("H", DEFAULT_NODE_COLOR)
    I = VisualUser("I", DEFAULT_NODE_COLOR)
    J = VisualUser("J", DEFAULT_NODE_COLOR)
    K = VisualUser("K", DEFAULT_NODE_COLOR)
    L = VisualUser("L", DEFAULT_NODE_COLOR)
    M = VisualUser("M", DEFAULT_NODE_COLOR)
    N = VisualUser("N", DEFAULT_NODE_COLOR)
    O = VisualUser("O", DEFAULT_NODE_COLOR)
    P = VisualUser("P", DEFAULT_NODE_COLOR)
    Q = VisualUser("Q", DEFAULT_NODE_COLOR)
    R = VisualUser("R", DEFAULT_NODE_COLOR)
    S = VisualUser("S", DEFAULT_NODE_COLOR)
    T = VisualUser("T", DEFAULT_NODE_COLOR)
    U = VisualUser("U", DEFAULT_NODE_COLOR)
    V = VisualUser("V", DEFAULT_NODE_COLOR)
    W = VisualUser("W", DEFAULT_NODE_COLOR)
    X = VisualUser("X", DEFAULT_NODE_COLOR)
    Y = VisualUser("Y", DEFAULT_NODE_COLOR)
    Z = VisualUser("Z", DEFAULT_NODE_COLOR)

    # Group 1
    A.add_student(B)
    A.add_student(C)
    A.add_student(D)
    B.add_student(E)
    B.add_student(F)
    C.add_student(F)
    D.add_student(G)
    F.add_student(C)
    E.add_student(A)

    # Group 2
    H.add_student(J)
    I.add_student(J)
    J.add_student(X)
    Y.add_student(H)

    # Group 3
    K.add_student(L)
    K.add_student(M)
    K.add_student(N)
    K.add_student(O)
    L.add_student(P)
    N.add_student(Q)
    N.add_student(R)
    N.add_student(S)
    N.add_student(V)
    S.add_student(T)
    T.add_student(U)
    V.add_student(W)
    S.add_student(W)
    O.add_student(Z)


    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)
    net.add_user(H)
    net.add_user(I)
    net.add_user(J)
    net.add_user(K)
    net.add_user(L)
    net.add_user(M)
    net.add_user(N)
    net.add_user(O)
    net.add_user(P)
    net.add_user(Q)
    net.add_user(R)
    net.add_user(S)
    net.add_user(T)
    net.add_user(U)
    net.add_user(V)
    net.add_user(W)
    net.add_user(X)
    net.add_user(Y)
    net.add_user(Z)

    return net


# Large Network
def network_3():
    A = VisualUser("A", DEFAULT_NODE_COLOR)
    B = VisualUser("B", DEFAULT_NODE_COLOR)
    C = VisualUser("C", DEFAULT_NODE_COLOR)
    D = VisualUser("D", DEFAULT_NODE_COLOR)
    E = VisualUser("E", DEFAULT_NODE_COLOR)
    F = VisualUser("F", DEFAULT_NODE_COLOR)
    G = VisualUser("G", DEFAULT_NODE_COLOR)
    H = VisualUser("H", DEFAULT_NODE_COLOR)
    I = VisualUser("I", DEFAULT_NODE_COLOR)
    J = VisualUser("J", DEFAULT_NODE_COLOR)
    K = VisualUser("K", DEFAULT_NODE_COLOR)
    L = VisualUser("L", DEFAULT_NODE_COLOR)
    M = VisualUser("M", DEFAULT_NODE_COLOR)
    N = VisualUser("N", DEFAULT_NODE_COLOR)
    O = VisualUser("O", DEFAULT_NODE_COLOR)
    P = VisualUser("P", DEFAULT_NODE_COLOR)
    Q = VisualUser("Q", DEFAULT_NODE_COLOR)
    R = VisualUser("R", DEFAULT_NODE_COLOR)
    S = VisualUser("S", DEFAULT_NODE_COLOR)
    T = VisualUser("T", DEFAULT_NODE_COLOR)
    U = VisualUser("U", DEFAULT_NODE_COLOR)
    V = VisualUser("V", DEFAULT_NODE_COLOR)
    W = VisualUser("W", DEFAULT_NODE_COLOR)
    X = VisualUser("X", DEFAULT_NODE_COLOR)
    Y = VisualUser("Y", DEFAULT_NODE_COLOR)
    Z = VisualUser("Z", DEFAULT_NODE_COLOR)
    AA = VisualUser("AA", DEFAULT_NODE_COLOR)
    AB = VisualUser("AB", DEFAULT_NODE_COLOR)
    AC = VisualUser("AC", DEFAULT_NODE_COLOR)
    AD = VisualUser("AD", DEFAULT_NODE_COLOR)
    AE = VisualUser("AE", DEFAULT_NODE_COLOR)
    AF = VisualUser("AF", DEFAULT_NODE_COLOR)
    AG = VisualUser("AG", DEFAULT_NODE_COLOR)
    AH = VisualUser("AH", DEFAULT_NODE_COLOR)
    AI = VisualUser("AI", DEFAULT_NODE_COLOR)
    AJ = VisualUser("AJ", DEFAULT_NODE_COLOR)
    AK = VisualUser("AK", DEFAULT_NODE_COLOR)
    AL = VisualUser("AL", DEFAULT_NODE_COLOR)
    AM = VisualUser("AM", DEFAULT_NODE_COLOR)
    AN = VisualUser("AN", DEFAULT_NODE_COLOR)
    AO = VisualUser("AO", DEFAULT_NODE_COLOR)
    AP = VisualUser("AP", DEFAULT_NODE_COLOR)

    # Group 1
    A.add_student(B)
    A.add_student(C)
    A.add_student(D)
    B.add_student(E)
    B.add_student(F)
    C.add_student(F)
    D.add_student(G)
    F.add_student(C)
    E.add_student(A)
    R.add_student(Y)
    H.add_student(J)
    I.add_student(J)
    J.add_student(X)
    Y.add_student(H)
    M.add_student(B)
    K.add_student(L)
    K.add_student(M)
    K.add_student(N)
    K.add_student(O)
    L.add_student(P)
    N.add_student(Q)
    N.add_student(R)
    N.add_student(S)
    N.add_student(V)
    S.add_student(T)
    T.add_student(U)
    V.add_student(W)
    S.add_student(W)
    O.add_student(Z)
    Y.add_student(AA)
    Y.add_student(AB)
    Y.add_student(AC)
    H.add_student(AD)
    X.add_student(AE)
    O.add_student(AF)
    M.add_student(AG)
    K.add_student(AH)
    K.add_student(AI)
    AA.add_student(AJ)
    AA.add_student(AK)
    AA.add_student(AL)
    AC.add_student(AM)
    AC.add_student(AN)
    AC.add_student(AO)
    AC.add_student(AP)


    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)
    net.add_user(H)
    net.add_user(I)
    net.add_user(J)
    net.add_user(K)
    net.add_user(L)
    net.add_user(M)
    net.add_user(N)
    net.add_user(O)
    net.add_user(P)
    net.add_user(Q)
    net.add_user(R)
    net.add_user(S)
    net.add_user(T)
    net.add_user(U)
    net.add_user(V)
    net.add_user(W)
    net.add_user(X)
    net.add_user(Y)
    net.add_user(Z)
    net.add_user(AA)
    net.add_user(AB)
    net.add_user(AC)
    net.add_user(AD)
    net.add_user(AE)
    net.add_user(AF)
    net.add_user(AG)
    net.add_user(AH)
    net.add_user(AI)
    net.add_user(AJ)
    net.add_user(AK)
    net.add_user(AL)
    net.add_user(AM)
    net.add_user(AN)
    net.add_user(AO)
    net.add_user(AP)

    return net


# Circular Network
def network_4():
    A = VisualUser("A", DEFAULT_NODE_COLOR)
    B = VisualUser("B", DEFAULT_NODE_COLOR)
    C = VisualUser("C", DEFAULT_NODE_COLOR)
    D = VisualUser("D", DEFAULT_NODE_COLOR)
    E = VisualUser("E", DEFAULT_NODE_COLOR)
    F = VisualUser("F", DEFAULT_NODE_COLOR)
    G = VisualUser("G", DEFAULT_NODE_COLOR)

    A.add_student(B)
    B.add_student(C)
    C.add_student(D)
    D.add_student(E)
    E.add_student(F)
    F.add_student(G)
    G.add_student(A)

    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)

    return net

############################################################

small_network = network_1()
medium_network = network_2()
large_network = network_3()
circular_network = network_4()