from visual_user import VisualUser, VisualNetwork, red

__author__ = 'Phillip Lemons'


## Network setup functions ################################
# Small Network
def network_1():
    A = VisualUser("A", red)
    B = VisualUser("B", red)
    C = VisualUser("C", red)
    D = VisualUser("D", red)
    E = VisualUser("E", red)
    F = VisualUser("F", red)
    G = VisualUser("G", red)
    H = VisualUser("H", red)
    I = VisualUser("I", red)
    J = VisualUser("J", red)

    A.add_student(B)
    A.add_student(C)
    A.add_student(D)
    B.add_student(E)
    B.add_student(F)
    C.add_student(F)
    D.add_student(G)
    H.add_student(J)
    I.add_student(J)

    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)
    net.add_user(H)
    net.add_user(I)
    net.add_user(J)

    return net


# Medium Network
def network_2():
    A = VisualUser("A", red)
    B = VisualUser("B", red)
    C = VisualUser("C", red)
    D = VisualUser("D", red)
    E = VisualUser("E", red)
    F = VisualUser("F", red)
    G = VisualUser("G", red)
    H = VisualUser("H", red)
    I = VisualUser("I", red)
    J = VisualUser("J", red)
    K = VisualUser("K", red)
    L = VisualUser("L", red)
    M = VisualUser("M", red)
    N = VisualUser("N", red)
    O = VisualUser("O", red)
    P = VisualUser("P", red)
    Q = VisualUser("Q", red)
    R = VisualUser("R", red)
    S = VisualUser("S", red)
    T = VisualUser("T", red)
    U = VisualUser("U", red)
    V = VisualUser("V", red)
    W = VisualUser("W", red)
    X = VisualUser("X", red)
    Y = VisualUser("Y", red)
    Z = VisualUser("Z", red)

    # Group 1
    A.add_student(B)
    A.add_student(C)
    A.add_student(D)
    B.add_student(E)
    B.add_student(F)
    C.add_student(F)
    D.add_student(G)
    F.add_student(C)
    E.add_student(A)

    # Group 2
    H.add_student(J)
    I.add_student(J)
    J.add_student(X)
    Y.add_student(H)

    # Group 3
    K.add_student(L)
    K.add_student(M)
    K.add_student(N)
    K.add_student(O)
    L.add_student(P)
    N.add_student(Q)
    N.add_student(R)
    N.add_student(S)
    N.add_student(V)
    S.add_student(T)
    T.add_student(U)
    V.add_student(W)
    S.add_student(W)
    O.add_student(Z)


    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)
    net.add_user(H)
    net.add_user(I)
    net.add_user(J)
    net.add_user(K)
    net.add_user(L)
    net.add_user(M)
    net.add_user(N)
    net.add_user(O)
    net.add_user(P)
    net.add_user(Q)
    net.add_user(R)
    net.add_user(S)
    net.add_user(T)
    net.add_user(U)
    net.add_user(V)
    net.add_user(W)
    net.add_user(X)
    net.add_user(Y)
    net.add_user(Z)

    return net


# Large Network
def network_3():
    A = VisualUser("A", red)
    B = VisualUser("B", red)
    C = VisualUser("C", red)
    D = VisualUser("D", red)
    E = VisualUser("E", red)
    F = VisualUser("F", red)
    G = VisualUser("G", red)
    H = VisualUser("H", red)
    I = VisualUser("I", red)
    J = VisualUser("J", red)
    K = VisualUser("K", red)
    L = VisualUser("L", red)
    M = VisualUser("M", red)
    N = VisualUser("N", red)
    O = VisualUser("O", red)
    P = VisualUser("P", red)
    Q = VisualUser("Q", red)
    R = VisualUser("R", red)
    S = VisualUser("S", red)
    T = VisualUser("T", red)
    U = VisualUser("U", red)
    V = VisualUser("V", red)
    W = VisualUser("W", red)
    X = VisualUser("X", red)
    Y = VisualUser("Y", red)
    Z = VisualUser("Z", red)
    AA = VisualUser("AA", red)
    AB = VisualUser("AB", red)
    AC = VisualUser("AC", red)
    AD = VisualUser("AD", red)
    AE = VisualUser("AE", red)
    AF = VisualUser("AF", red)
    AG = VisualUser("AG", red)
    AH = VisualUser("AH", red)
    AI = VisualUser("AI", red)
    AJ = VisualUser("AJ", red)
    AK = VisualUser("AK", red)
    AL = VisualUser("AL", red)
    AM = VisualUser("AM", red)
    AN = VisualUser("AN", red)
    AO = VisualUser("AO", red)
    AP = VisualUser("AP", red)

    # Group 1
    A.add_student(B)
    A.add_student(C)
    A.add_student(D)
    B.add_student(E)
    B.add_student(F)
    C.add_student(F)
    D.add_student(G)
    F.add_student(C)
    E.add_student(A)
    R.add_student(Y)
    H.add_student(J)
    I.add_student(J)
    J.add_student(X)
    Y.add_student(H)
    M.add_student(B)
    K.add_student(L)
    K.add_student(M)
    K.add_student(N)
    K.add_student(O)
    L.add_student(P)
    N.add_student(Q)
    N.add_student(R)
    N.add_student(S)
    N.add_student(V)
    S.add_student(T)
    T.add_student(U)
    V.add_student(W)
    S.add_student(W)
    O.add_student(Z)
    Y.add_student(AA)
    Y.add_student(AB)
    Y.add_student(AC)
    H.add_student(AD)
    X.add_student(AE)
    O.add_student(AF)
    M.add_student(AG)
    K.add_student(AH)
    K.add_student(AI)
    AA.add_student(AJ)
    AA.add_student(AK)
    AA.add_student(AL)
    AC.add_student(AM)
    AC.add_student(AN)
    AC.add_student(AO)
    AC.add_student(AP)


    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)
    net.add_user(H)
    net.add_user(I)
    net.add_user(J)
    net.add_user(K)
    net.add_user(L)
    net.add_user(M)
    net.add_user(N)
    net.add_user(O)
    net.add_user(P)
    net.add_user(Q)
    net.add_user(R)
    net.add_user(S)
    net.add_user(T)
    net.add_user(U)
    net.add_user(V)
    net.add_user(W)
    net.add_user(X)
    net.add_user(Y)
    net.add_user(Z)
    net.add_user(AA)
    net.add_user(AB)
    net.add_user(AC)
    net.add_user(AD)
    net.add_user(AE)
    net.add_user(AF)
    net.add_user(AG)
    net.add_user(AH)
    net.add_user(AI)
    net.add_user(AJ)
    net.add_user(AK)
    net.add_user(AL)
    net.add_user(AM)
    net.add_user(AN)
    net.add_user(AO)
    net.add_user(AP)

    return net


# Circular Network
def network_4():
    A = VisualUser("A", red)
    B = VisualUser("B", red)
    C = VisualUser("C", red)
    D = VisualUser("D", red)
    E = VisualUser("E", red)
    F = VisualUser("F", red)
    G = VisualUser("G", red)

    A.add_student(B)
    B.add_student(C)
    C.add_student(D)
    D.add_student(E)
    E.add_student(F)
    F.add_student(G)
    G.add_student(A)

    net = VisualNetwork()
    net.add_user(A)
    net.add_user(B)
    net.add_user(C)
    net.add_user(D)
    net.add_user(E)
    net.add_user(F)
    net.add_user(G)

    return net

############################################################

small_network = network_1()
medium_network = network_2()
large_network = network_3()
circular_network = network_4()